//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZCL.RTScript {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZCL.RTScript.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Marker is not found while paring this Expression List..
        /// </summary>
        internal static string Expression_List_End_Marker_Missing {
            get {
                return ResourceManager.GetString("Expression_List_End_Marker_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve application target to a function name nor a scope..
        /// </summary>
        internal static string Function_Apply_Invalid_Target {
            get {
                return ResourceManager.GetString("Function_Apply_Invalid_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No library function with the name {0} is found..
        /// </summary>
        internal static string Function_Apply_No_Metadata {
            get {
                return ResourceManager.GetString("Function_Apply_No_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first argument of a def function call must be a symbol..
        /// </summary>
        internal static string Function_Def_Arg0 {
            get {
                return ResourceManager.GetString("Function_Def_Arg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller function of Def has no scope..
        /// </summary>
        internal static string Function_Def_Caller_No_Scope {
            get {
                return ResourceManager.GetString("Function_Def_Caller_No_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function end bracket is missing..
        /// </summary>
        internal static string Function_End_Bracket_Missing {
            get {
                return ResourceManager.GetString("Function_End_Bracket_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert condition value to boolean..
        /// </summary>
        internal static string Function_If_Null_Condition {
            get {
                return ResourceManager.GetString("Function_If_Null_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse argument &apos;{0}&apos;..
        /// </summary>
        internal static string Function_Invalid_Arg {
            get {
                return ResourceManager.GetString("Function_Invalid_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid identifier..
        /// </summary>
        internal static string Function_Invalid_Arg_Identifier {
            get {
                return ResourceManager.GetString("Function_Invalid_Arg_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid number..
        /// </summary>
        internal static string Function_Invalid_Arg_Number {
            get {
                return ResourceManager.GetString("Function_Invalid_Arg_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Marker is not found while paring this Function List..
        /// </summary>
        internal static string Function_List_End_Marker_Missing {
            get {
                return ResourceManager.GetString("Function_List_End_Marker_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Name cannot be of token type {0}..
        /// </summary>
        internal static string Function_Name_Missing {
            get {
                return ResourceManager.GetString("Function_Name_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting an open bracket to parse a function..
        /// </summary>
        internal static string Function_Open_Bracket_Missing {
            get {
                return ResourceManager.GetString("Function_Open_Bracket_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} of function {1} cannot be a function..
        /// </summary>
        internal static string Metadata_Invalid_Arg_Func {
            get {
                return ResourceManager.GetString("Metadata_Invalid_Arg_Func", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} of function {1} cannot be a list..
        /// </summary>
        internal static string Metadata_Invalid_Arg_List {
            get {
                return ResourceManager.GetString("Metadata_Invalid_Arg_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid enumerator position..
        /// </summary>
        internal static string Metadata_List_Enum_Error {
            get {
                return ResourceManager.GetString("Metadata_List_Enum_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function needs at least {0} arguments, but got {1}..
        /// </summary>
        internal static string Metadata_Not_Enough_Args {
            get {
                return ResourceManager.GetString("Metadata_Not_Enough_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function accepts at most {0} arguemnts, but got {1}..
        /// </summary>
        internal static string Metadata_Too_Many_Args {
            get {
                return ResourceManager.GetString("Metadata_Too_Many_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error(s) occurred in post execution..
        /// </summary>
        internal static string Post_Execution_Error {
            get {
                return ResourceManager.GetString("Post_Execution_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse post template..
        /// </summary>
        internal static string Post_Parsing_Error {
            get {
                return ResourceManager.GetString("Post_Parsing_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call ArgCount on a scope that is not created for a RTFunction..
        /// </summary>
        internal static string Scope_ArgCount_Error {
            get {
                return ResourceManager.GetString("Scope_ArgCount_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call Execute on a scope that is not created for a RTFunction..
        /// </summary>
        internal static string Scope_Execute_Error {
            get {
                return ResourceManager.GetString("Scope_Execute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call GetArg on a scope that is not created for a RTFunction..
        /// </summary>
        internal static string Scope_GetArg_Error {
            get {
                return ResourceManager.GetString("Scope_GetArg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error(s) occurred in template execution..
        /// </summary>
        internal static string Template_Execution_Error {
            get {
                return ResourceManager.GetString("Template_Execution_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse template..
        /// </summary>
        internal static string Template_Parsing_Error {
            get {
                return ResourceManager.GetString("Template_Parsing_Error", resourceCulture);
            }
        }
    }
}
